plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'jarvis.Jarvis'
}

dependencies {
    String junitVersion = '5.14.4'

    testImplementation "org.junit.jupiter:junit-jupiter-api:${junitVersion}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.14.4'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('test', Test) {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed'
        showExceptions = true
        exceptionFormat = 'full'
        showCauses = true
        showStackTraces = true
        showStandardStreams = false
    }
}

tasks.named('run', JavaExec) {
    standardInput = System.in
    systemProperty 'jarvis.storage', System.getProperty('jarvis.storage', 'data/jarvis.txt')
    jvmArgs '-Dfile.encoding=UTF-8', '-Dstdout.encoding=UTF-8'
}
